// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Activity, UserCircle } from "lucide-react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hackathon Trailblazer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900 flex flex-col min-h-screen`}
      >
        {/* Navigation Bar - Clean, Minimal, White */}
        <nav className="flex items-center justify-between px-6 py-4 bg-white w-full z-10">
          {/* Logo (Left) */}
          <Link
            href="/"
            className="flex items-center gap-2 p-2 rounded-full transition-transform hover:scale-105"
          >
            {/* Matches the green heartbeat in your image */}
            <Activity size={32} strokeWidth={2.5} color="#7BA63F" />
          </Link>

          {/* Profile Icon (Right) */}
          <Link
            href="/userprofile"
            className="flex items-center gap-2 p-2 rounded-full transition-transform hover:scale-105"
          >
            {/* Matches the profile icon in your image */}
            <UserCircle size={32} strokeWidth={2.0} color="#7BA63F" />
          </Link>
        </nav>

        {/* Main Content Area - flex-1 ensures it fills the rest of the screen */}
        <main className="flex-1 w-full flex flex-col">{children}</main>
      </body>
    </html>
  );
}
