import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Activity, UserCircle } from "lucide-react";
import "./globals.css";
import { getUserSession } from "@/backend/server";
import UserDropdown from "@/app/component/userdropdown"; // client component
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hackathon Trailblazer",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const user = await getUserSession(); // server-side

  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-gray-900 flex flex-col min-h-screen`}
      >
        <nav className="flex items-center justify-between px-6 py-4 bg-white border-b-2 border-[#7BA63F] w-full z-10">
          <Link
            href="/"
            className="flex items-center gap-2 p-2 rounded-full transition-transform hover:scale-105"
          >
            <Activity size={32} strokeWidth={2.5} color="#7BA63F" />
          </Link>

          {user ? (
            <UserDropdown userEmail={user.email || ""} />
          ) : (
            <UserCircle size={32} strokeWidth={2} color="#7BA63F" />
          )}
        </nav>

        <main className="flex-1 w-full flex flex-col">{children}</main>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}